language: swift
osx_image: xcode11.2
cache:
- bundler
- cocoapods
before_install:
- bundle install
- bundle exec pod keys set MarvelApiKey $MARVEL_API_SECRET Marvel
- bundle exec pod keys set MarvelPrivateKey $MARVEL_API_PUBLIC Marvel
- pod repo update
script:
- fastlane test
- bundle exec danger
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: Gjczd0VbiZxVJYaACty2ALhXr0COD9BiqhLHKxA3EBdbYOd4LTxYMCVrDXv3x1f8omjcgt6iXzLQx4SwpJGESQWBfawCSP9nZQTx0zlOlC0KboOGOfQyMxJeeJc5Z/4FPd79GqZ/xluOK61i/C4aNq+bGHvIX4cM32y5jzRFzusyE5XGWpGnxkIsJOTm6h8zE6vYoMcHav8fWoL739YxXXRunDiNBsBcW3nIhfS6wm+4FY10i2y/gCiUwqeclFVMLdO1rDZ3HXrm6hVtjiQXUthCBM5809ylEn4BQ27szfEWdOSQIwoXVPSrv2fvQHT60VFGaAzCdmwJa9F9ADs9GWOW7rR/tOnTDDvrolIyH3fGRdXXuPZwRKbfHbdrtyu0zSvXO6qADpFZqzsDCYe56XinJwkvL0TpoFZ4aRaYd+KqBcpzpOPJaoKqFgfSvdFPfDjFwWylj/AwBfxl9cbHCXnh647x33Jnhiwgao56ovqgRv16AbHWz+VoPGTa7K5kdl37OfkSlmdn/yjMEdvn2MLDwx5CkClz0FJJwWRaJgNGqjNILEycreTqF6UI8SwUYQMc018D4vtr9k2jngi83/oIlnlxRVvhdAaCW8n0mc4Raq8OQn9NEj9EtTsxB2MeNunHB2hsFPqoKzUTffFqUQWuyMb/ae0LKn03CJA3xf8=
  - secure: qfYNTQzvX6rvZ3ao8DbxL+9wFcG2mv0M5r1jY/uIsUzzG1T85VJpnsUv4VcGtd5yJ2FdKpHik/cAk1Lq6rV4xD1+eGecm2b2C25zOnNyljT01ZqfYhK8yaHrGqmZ+N7RFxYzM1wkzprJsWQU+GrZ0bjk5MfTu5HeuZh3HddyNzsFvJT5XqMM/yzIsfo/4Z57y4vVZZUimEDypNNT5ADYo740lVO3EHq6lQSEEoOZG4sY9K5o2wW7V5voyGQu4ytqbZ+UNthgOIcfYmjL9r7L3XAlLYKvpuX0U7UNpgcaw9P4KJJa3zGR36ptV3+KEz3e/3D+xLz8RyyTAguIbXcrrMS1A6tVQkBCjegXvYA5NSFfuz3Ycs77d/n4++y5oohFiVehtiST6ZI8PxC4qVNDm3CsI3TnG92gi/j6NQDqiFcSmnajbJYUuWUbKDI0zD9J8keewFXhsu/AHF4xUldligI5kifthFICWUHjLtlhvHF1QtRtKiBbYvqMsfyTDIgMUjYBtpfBzObUob1bIsfN48HgeEj9t+qW7ROyc1ZVJADhDDn+IcBaQpiKzIhy94L7lwLyU2kJPKw1mvJZ9mdhq2RmUQusK9/KJu1yHHfn36oRj9KguRf81HD8lWSZQIWyQZgFRxG599CZUlnA7jEPN83ve8F9VgmTpi6cHyjTmgU=
